### ISSUE TITLE
Some problems that arise when running the FewRel dataset， FewRel データセットの実行時に発生するいくつかの問題

### ISSUE THREAD

**Issue by huguanghong** [vhientran/Code-ZSRE#1]
Hello, thank you very much for your open source code, I learned a lot from it, I have no problem when running the wiki data set, but when running FewRel it reminds me that there is no Pid2name_fewrel.json, I built Pid2name_fewrel based on the property_list.html under official_data. json, but after running it, the f1 score has always been 0.06666..7. I want to know if there is a problem with the Pid2name_fewrel.json I built. Could you please add this file to the code base? Thank you very much! I wish you all the best。
こんにちは、オープン ソース コードをありがとうございます。そこから多くのことを学びました。Wiki データ セットを実行するときは問題ありませんが、FewRel を実行すると、Pid2name_fewrel.json がないことを思い出させられます。私は、以下に基づいて Pid2name_fewrel.json を構築しました。 official_data.json の下に property_list.html がありましたが、実行後、f1 スコアは常に 0.06666..7 でした。私が構築した Pid2name_fewrel.json に問題があるかどうか知りたいのですが、このファイルをコードベース?ありがとうございます! あなたの人生に幸あれ

**Comment by vhientran** [comment]
Hi @hgh-xxh 

Thank you for your interest on my work. I have just uploaded the file pid2name_fewrel.json, and you can access it at: https://github.com/vhientran/Code-ZSRE/tree/main/official_data . 
If there are any problems, feel free to let me know.
Thank you!

**Comment by huguanghong** [comment]
Wow, the code runs perfectly, thank you very much for your help!

**Comment by vhientran** [comment]
If there is no problem, then I will close this issue.
