### ISSUE TITLE
About the file official_data_divisions.json ファイルofficial_data_divisions.jsonについて

### ISSUE THREAD

**Issue by huguanghong** [vhientran/Code-ZSRE#2]
Hello author! When I read the ZS-BERT source code, I found that when selecting unseen relationships, the source code uses the random function to randomly select. However, the author's code selects a collection in official_data_divisions.json. Why is it designed like this?
著者さん、こんにちは！ ZS-BERTのソースコードを読んでみると、ソースコードでは目に見えない関係を選択する際にrandom関数を使ってランダムに選択しているのですが、なぜこのような仕様になっているのでしょうか？

**Comment by vhientran** [comment]
Hi @hgh-xxh 
Thank you for your interesting question. Given the total of N relation types, the authors in doing research on Zero-Shot Relation Extraction often divide it into K relation types for testing set and (N-K) relation types for training set. 
In the ZS-BERT source code, the authors also used the random function to select K unseen relations for testing, but they did not provide these K unseen relations to research community. It causes diffifult for future works when the future works want to evaluate and compare their model performance on the same K unseen relations used in the ZS-BERT work. This is the only way to guarantee a fair comparison between the baseline model and future works.
Thus, we also randomly select K unseen relations for testing, but we want to release this set for future works, as they can compare to our model performance in a fair comparison.
I hope my explaination is clear with you. Let me know if anything is unclear.

**Comment by huguanghong** [comment]
Thanks for your answer, I understand！！

**Comment by vhientran** [comment]
Then, I will close this issue. Thank you.
